spring:
  application:
    name: journalApp
  datasource:
    url: jdbc:mysql://localhost:3306/journals_db
    username: root
    password: M0use@2001
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


